services:
  layer-api-green:
    image: docker.io/clean01/layer-server_layer-api:latest
    container_name: layer-api-green
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./application-secret.properties:/config/application-secret.properties
      - ./log:/log
      - ./tokens:/config/tokens
    networks:
      - app-network

  batch-job-green:
    image: docker.io/clean01/layer-server_layer-batch:latest
    container_name: layer-batch-green
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./application-secret.properties:/config/application-secret.properties
      - ./log:/log
      - ./tokens:/config/tokens
    networks:
      - app-network
    depends_on:
      - layer-api-green
    restart: always

networks:
  app-network: