services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
    volumes:
      - redis-data:/data # Persistent data storage
    restart: always
    networks:
      - app-network

  layer-api-prod-green:
    image: docker.io/clean01/layer-server_layer-api:latest
    container_name: layer-api-prod-green
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./application-secret.properties:/config/application-secret.properties
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:

volumes:
  redis-data: