services:
  blue:
    image: docker.io/clean01/layer-server_layer-api:latest
    container_name: blue
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./application-secret.properties:/config/application-secret.properties
      - ./log:/log
      - ./tokens:/config/tokens
    networks:
      - app-network

  batch-job:
    image: docker.io/clean01/layer-server_layer-batch:latest
    container_name: layer-batch_blue
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./application-secret.properties:/config/application-secret.properties
      - ./log:/log
      - ./tokens:/config/tokens
    networks:
      - app-network
    depends_on:
      - blue
      - green
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - blue
      - green
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network: