services:
  layer-api-blue:
    image: docker.io/clean01/layer-server_layer-api:latest
    container_name: layer-api-blue
    ports:
      - "8080:8081"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./application-secret.properties:/config/application-secret.properties
      - ./log:/log
      - ./tokens:/config/tokens
    networks:
      - app-network

  batch-job-blue:
    image: docker.io/clean01/layer-server_layer-batch:latest
    container_name: layer-batch-blue
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./application-secret.properties:/config/application-secret.properties
      - ./log:/log
      - ./tokens:/config/tokens
    networks:
      - app-network
    depends_on:
      - layer-api-blue
    restart: always

  nginx-blue:
    image: nginx:latest
    container_name: nginx-blue
    depends_on:
      - layer-api-blue
      - batch-job-blue
    ports:
      - "80:80"
    volumes:
      - ./nginx.blue.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network: