server:
  port: 3000

spring:
  config:
    import: application-secret.properties
  datasource:
    url: ${AWS_DEV_DB_URL}
    username: ${AWS_PROD_DB_NAME}
    password: ${AWS_PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5  # 최대 pool 크기
      minimum-idle: 5  # 최소 pool 크기
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    database: mysql

admin:
  password: ${ADMIN_PASSWORD}