spring:
  config:
    import: optional:file:/config/application-secret.properties
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_NAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    database: mysql

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      password: ${DEV_REDIS_PASSWORD}

jwt:
  secret: ${DEV_JWT_SECRET}

kakao:
  login:
    api_key: ${DEV_KAKAO_API_KEY}
    redirect_uri: ${DEV_KAKAO_REDIRECT_URI}
    uri:
      base: https://kauth.kakao.com
      code: /oauth/authorize
      token: /oauth/token
  api:
    uri:
      base: https://kapi.kakao.com
      user: /v2/user/me

google:
  login:
    client_id: ${DEV_GOOGLE_CLIENT_ID}
    code_uri: ${DEV_GOOGLE_CODE_URI}
    token_uri: ${DEV_GOOGLE_TOKEN_URI}
    client_secret: ${DEV_GOOGLE_CLIENT_SECRET}
    redirect_uri: ${DEV_GOOGLE_REDIRECT_URI}
    code_redirect_uri: http://localhost:8080/api/auth/oauth2/google/code


webmvc:
  cors:
    allowedOrigins:
      http://localhost:8080,
      https://api.layerapp.io,
      https://layerapp.io,
      http://localhost:5173

ncp:
  storage:
    region: ${STORAGE_REGION}
    bucketName: ${STORAGE_NAME}
    endpoint: ${STORAGE_ENDPOINT}
    accessKey: ${STORAGE_ACCESS_KEY}
    secretKey: ${STORAGE_SECRET_KEY}