spring:
  config:
    import: optional:file:/config/application-secret.properties
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_NAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    database: mysql

  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}
      password: ${PROD_REDIS_PASSWORD}

jwt:
  secret: ${PROD_JWT_SECRET}

kakao:
  login:
    api_key: ${DEV_KAKAO_API_KEY}
    redirect_uri: ${DEV_KAKAO_REDIRECT_URI}
    uri:
      base: https://kauth.kakao.com
      code: /oauth/authorize
      token: /oauth/token
  api:
    uri:
      base: https://kapi.kakao.com
      user: /v2/user/me

google:
  login:
    client_id: ${DEV_GOOGLE_CLIENT_ID}
    client_secret: ${DEV_GOOGLE_CLIENT_SECRET}
    redirect_uri: ${DEV_GOOGLE_REDIRECT_URI}
  sheet:
    id: ${GOOGLE_SHEET_ID}
    token_path: ${PROD_GOOGLE_TOKEN_PATH}
    credential_path: ${PROD_GOOGLE_CREDENTIAL_PATH}

apple:
  login:
    issuer: ${DEV_APPLE_ISSUER}
    client_id: ${DEV_APPLE_CLIENT_ID}
    audience: ${DEV_APPLE_AUD}

webmvc:
  cors:
    allowedOrigins:
      http://localhost:8080,
      https://api.layerapp.io,
      https://layerapp.io,
      http://localhost:5173

ncp:
  storage:
    region: ${STORAGE_REGION}
    bucketName: ${STORAGE_NAME}
    endpoint: ${STORAGE_ENDPOINT}
    accessKey: ${STORAGE_ACCESS_KEY}
    secretKey: ${STORAGE_SECRET_KEY}

openai:
  systemContent: ${OPENAI_SYSTEM_CONTENT}
  apiKey: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL}
  maxTokens: ${OPENAI_MAX_TOKENS}