services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
    volumes:
      - redis-data:/data # Persistent data storage
    restart: always
    networks:
      - app-network

  layer-api-green:
    image: docker.io/clean01/layer-server_layer-api:latest
    container_name: layer-api-green
    ports:
      - "8090:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./application-secret.properties:/config/application-secret.properties
      - ./tokens:/config/tokens
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:

volumes:
  redis-data: